# Generated by Django 5.0.4 on 2024-05-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="dni",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
