# Generated by Django 4.2.11 on 2024-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0004_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(max_length=11),
        ),
    ]
