# Generated by Django 5.0.4 on 2024-05-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modulo", "0005_alter_empresa_ruc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("numero_factura", models.CharField(max_length=20, unique=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="modulo.cliente"
                    ),
                ),
                ("productos", models.ManyToManyField(to="modulo.producto")),
            ],
        ),
    ]
