# Generated by Django 4.2.11 on 2024-05-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0006_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='numero_factura',
        ),
    ]
